version: '2.0'
services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    container_name: npl-on-wechat
    security_opt:
      - seccomp:unconfined
    ports:
      - "3001:3000"  # 本地端口3001映射到容器端口3000
    environment:
      # 启用智谱 AI
      USE_ZHIPU_AI: 'True'
      ZHIPU_AI_API_KEY: '*****'  # 请替换为您的实际密钥
      ZHIPU_AI_API_BASE: 'https://open.bigmodel.cn/api/paas/v4/'
      MODEL: 'glm-4'  # 智谱 AI 的模型名称
      # 禁用其他模型
      USE_OPENAI: 'False'
      USE_MOONSHOT: 'False'
      USE_KIMI: 'False'
      # 其他配置
      CHANNEL_TYPE: 'wx'
      PROXY: ''  # 如果需要代理，请在此填写，例如 'http://127.0.0.1:7890'
      HOT_RELOAD: 'False'
      SINGLE_CHAT_PREFIX: '[""]'
      SINGLE_CHAT_REPLY_PREFIX: '" "'
      GROUP_CHAT_PREFIX: '["@bot","bot"]'
      GROUP_NAME_WHITE_LIST: '["ALL_GROUP"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      CONVERSATION_MAX_TOKENS: 4000
      SPEECH_RECOGNITION: 'True'
      CHARACTER_DESC: '你是江老师研发的智能助理。我的主要职责是提供热情而专业的帮助，解答你关于学术、科研、生活等方面的各种疑问。我拥有广博的知识和丰富的资源，能够以多种语言与你进行流畅的交流。我会竭尽全力理解你的问题，并为你提供最准确、最有用的信息。请随时向我提出问题，我总是在这里，准备帮助你。'
      SUBSCRIBE_MSG: '感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。'
      EXPIRES_IN_SECONDS: 3600
      USE_GLOBAL_PLUGIN_CONFIG: 'True'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
